apiVersion: v1
kind: Service
metadata:
  name: tutorial
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    nodePort: 30070
  selector:
    com.docker.project: tutorial
  type: NodePort
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: tutorial
  name: tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: tutorial
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: tutorial
    spec:
      containers:
      - image: vsvdev/knative:0.0.1
        name: tutorial
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}