apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: orders-function
spec:
  template:
    spec:
      containers:
        - name: orders-function
          image: vsvdevua/knative:0.0.1
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '2'
              memory: '512Mi'