apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: orders-function
spec:
  template:
    spec:
      containers:
        - name: orders-function
          image: vsvdevua/knative:1
          ports:
            - containerPort: 9000
          env:
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: kangular-app-config
                  key: ORIGIN
            - name: JAVA_TOOL_OPTIONS
              value: "-Xss512K"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
